config/routes.rb
CompanyDirectory::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_admin?
      can :access, :rails_admin   # grant access to rails_admin
    end
    can :dashboard              # grant access to the dashboard
    can :read, :all
    can :manage, :all
  end
end

app/models/accessible_entity.rb
class AccessibleEntity < ActiveRecord::Base
  has_many :role_accessible_entities
  has_many :roles, through: :role_accessible_entities

  validates :name, uniqueness: true
end

app/models/accessible_model.rb
class AccessibleModel < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :name, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_accessible_entities
  has_many :accessible_entities, through: :role_accessible_entities

end

app/models/role_accessible_entity.rb
class RoleAccessibleEntity < ActiveRecord::Base
  belongs_to :role
  belongs_to :accessible_entity
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :omniauthable
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :trackable,
          :validatable,
          # :confirmable
          :timeoutable

  USER_TYPES = ['Employee', 'Student']

  def is_admin?
    admin ? admin : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/', :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :phone_number
    devise_parameter_sanitizer.for(:account_update) << :user_type
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- Main component for a primary marketing message or call to action -->
<%- if current_user %>
  <div class="jumbotron">
    <h1>YOU IS A USER. <br>YOU IS LOGGED IN.</h1>
  </div>
  <ul>
    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>

  </ul>

<%- else %>
  <div class="jumbotron">
    <h1><%= t(:title) %></h1>
    <p><%= t(:description) %></p>
    <p>
      <%= link_to t(:register), new_user_registration_path, class: "btn btn-lg btn-primary", role: "button" %>
    </p>
  </div>
  <div>
    <h3><%= t('open_source.title') %></h3>
    <%= link_to t('open_source.github.title'), t('open_source.github.link') %>
  </div>
<%- end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <%= link_to "The Iron Yard", root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<li><a href="#about"><%= t('navbar.employees') %></a></li>
<li><a href="#contact"><%= t('navbar.students') %></a></li>

app/views/layouts/_navigation_links_right.html.erb
<%- if user_signed_in? %>
  <%- if current_user.is_admin? -%>
    <li><%= link_to t(:admin_text), rails_admin_path %></li>
  <%- end %>
  <li><%= link_to t(:edit), edit_user_registration_path %></li>
  <li><%= link_to t(:log_out), destroy_user_session_path, method: :delete %></a></li>
<%- else %>
  <li><%= link_to t(:log_in), new_user_session_path %></li>
  <li><%= link_to t(:register), new_user_registration_path %></a></li>
<%- end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Company Directory" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Company Directory" %>">
    
    <link href="/assets/favicon.png" rel="icon">
    
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body style="">

    <!-- Static navbar -->
    <%= render 'layouts/navigation' %>


    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div> <!-- /container -->

    <div id="footer">
      <div class="container">
        <p class="text-muted">©2014 The Iron Yard. All Rights Reserved</p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  
  </body>
</html>